name: Reusable workflow
on:
    workflow_call:
        inputs:
            name:
                description: 'Input description'
                type: string
                default: 'Pradnya'
                required: false
        secrets:
            access-token:
                description: 'secret description'
                required: true

jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: ls -a
    log-context-and-inputs:
        runs-on: ubuntu-latest
        steps:
            - name: display github context
              run: echo '${{ toJson(github) }}'
            - name: display name input
              run: echo ${{ inputs.name }}
            - name: display access token secret 
              run: echo ${{ secrets.access-token }}
