name: status check functions
on: [push]

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: step 1
              run: sleep 20
            - name: step 2
              id: step-2
              continue-on-error: true
              run: exit 1
            - name: runs on step 2 failure
              if: failure() && steps.step-2.conclusion == 'failure'
              run: echo 'step 2 has failed'
            - name: runs on failure
              if: failure()
              run: echo 'failure'
            - name: runs on success
            # this is not needed (dafault behaviour) 
              if: success()
              run: echo 'runs on success'
            - name: always runs
            #   if: success() || failure()
              if: always()
              run: echo 'always runs'
            - name: runs when clanelled
              if: cancelled()
              run: echo 'runs on cancelled'
    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        if: failure()
        steps:
            - run: echo 'job 2'