name: calling reusable workflow
on: 
    workflow_dispatch:
        inputs:
            name:
                description: 'Input description'
                type: string
                default: 'Pradnya'
                required: false
jobs:
    calling-reusable-wf:
        uses: pradnyaakumbhar/GithubActions/.github/workflows/reusable.yaml@main
        with:
            name: ${{ inputs.name }}
        secrets:
            access-token: ${{ secrets.ACCESS_TOKEN }}
    calling-a-reusable-wf-in-the-same-repo:
        uses: pradnyaakumbhar/GithubActions/.github/workflows/reusable-workflow.yaml@main
    using-reusable-wf-output:
        runs-on: ubuntu-latest
        needs: calling-a-reusable-wf-in-the-same-repo
        steps:
            - run: echo ${{ needs.calling-a-reusable-wf-in-the-same-repo.outputs.date }}